### ISSUE TITLE
Feature request: Esc key to cancel

### ISSUE THREAD

**Issue by cpoakes** [BunsenLabs/bunsen-exit-old#3]
Most dialog boxes with a cancel or close button (for example the gtk2 and gtk3 file choosers, the zenity dialogs, gimp dialogs, libreoffice dialogs, gnome applications dialogs) accept the Escape key to cancel.  Script bl-exit could easily do the same.  

Required code (suggested after Cancel button block):

```
#Cancel key (Esc)
accelgroup = gtk.AccelGroup()
key, mod = gtk.accelerator_parse('Escape')
accelgroup.connect_group(key, mod, gtk.ACCEL_VISIBLE, gtk.main_quit)
self.window.add_accel_group(accelgroup)
```

**Comment by ghost** [comment]
Thanks for the snippet, cancelling when pressing Esc makes sense.

I'm foreign to Python, but it seems that accelerator_parse() returns a tuple of values (key, mod) which is being unpacked using an intermediate assignment.

For elegance, would it be possible to somehow unpack without an extra assignment? The obvious modification

``` python
accelgroup.connect_group(gtk.accelerator_parse('Escape'), ...)
```

doesn't work as expected (in Lua it would), so I'm wondering if there is an elegant Python way for achieving the same?

**Comment by cpoakes** [comment]
You want the unpack operator:

```
accelgroup.connect_group(*gtk.accelerator_parse('Escape'), gtk.ACCEL_VISIBLE, gtk.main_quit)
```

but this pukes within the function call:

```
SyntaxError: only named arguments may follow *expression
```

Corrected:

```
accelgroup.connect_group(*gtk.accelerator_parse('Escape'), accel_flags=gtk.ACCEL_VISIBLE, callback=gtk.main_quit)
```

Now the question: does this meet your definition of elegance?  I find the syntax obtuse.

**Comment by ghost** [comment]
Aaah, Python's less neat than expected in that regard. OK, I'll keep the current implementation since a) there's less to type and b) it's easier to read.

Thanks for the follow-up.
