### ISSUE TITLE
Single agnostic exit command

### ISSUE THREAD

**Issue by cpoakes** [BunsenLabs/bunsen-exit-old#4]
Per johnraff in [this CrunchBang posting](http://crunchbang.org/forums/viewtopic.php?pid=424389#p424389)

> ... It was still easy to look through that script, find the system calls and replace the dbus commands with systemctl ones. If there was a single command that worked on all init systems and did not require the editing of sudoers, then for sure  I would recommend we use it. 

The following patch is requested:

```
8a9,10
> dbus_send = "dbus-send --print-reply --system --dest=org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.{} boolean:true"
> 
30c32
<         os.system("systemctl suspend")

---
>          os.system(dbus_send.format("Suspend"))
36c38
<         os.system("systemctl reboot")

---
>         os.system(dbus_send.format("Reboot"))
41c43
<         os.system("systemctl poweroff")

---
>         os.system(dbus_send.format("PowerOff"))
```

This dbus-send command is a request to the org.freedesktop.login1.service, a service supplied by the systemd package.  This command is valid for systems using either systemd-sysv as systemd init or systemd-shim with another init system.

**Comment by ghost** [comment]
@BunsenLabs/config-team We need to test this.

**Comment by johnraff** [comment]
Reboot and poweroff options confirmed working on VirtualBox netinstall BL with systemd. (Suspend causes freezes on this setup.)

**Comment by Sector11** [comment]
Reboot and poweroff - work as expected

Suspend leaves my "desktop" with a blinking cursor but then one doesn't suspend a Desktop.
